#!/bin/bash

# .bashrc
# .inputrc
# .vimrc

TMH=$HOME/take-me-home
BACKUPS=$TMH/backups

if [ -f $BACKUPS/original-bashrc.bkp ] ; then
    cp $BACKUPS/original-bashrc.bkp ~/.bashrc
fi

if [ -f $BACKUPS/original-inputrc.bkp ] ; then
    cp $BACKUPS/original-inputrc.bkp ~/.inputrc
fi

if [ -f $BACKUPS/original-vimrc.bkp ] ; then
    cp $BACKUPS/original-vimrc.bkp ~/.vimrc
fi

rm -rf ~/take-me-home

echo done.
