#!/bin/bash

# .bashrc
# .inputrc
# .vimrc
# This script restores original files from the backup folder to $HOME (~/)

BACKUPS=$HOME/take-me-home/backups

# Restore .bashrc
if [ -f $BACKUPS/original-bashrc.bkp ] ; then
    rm ~/.bashrc
    cp $BACKUPS/original-bashrc.bkp ~/.bashrc
    source ~/.bashrc
fi

# Restore .inputrc
if [ -f $BACKUPS/original-inputrc.bkp ] ; then
    rm ~/.inputrc
    cp $BACKUPS/original-inputrc.bkp ~/.inputrc
fi

# Restore .vimrc
if [ -f $BACKUPS/original-vimrc.bkp ] ; then
    rm ~/.vimrc
    cp $BACKUPS/original-vimrc.bkp ~/.vimrc
fi

rm -rf ~/take-me-home

echo done.

unset BACKUPS
