#!/usr/bin/env bash

#.=.=.=.=.=.=.=
# Take Me Home
#.=.=.=.=.=.=.=
# * Refresh-distro
# * Install git, node, npm
# * Create "~/take-me-home" folder
# * Create "~/take-me-home/backups" folder
# * Backup and hard link: .bashrc/.inputrc/.vimrc
# * Hard link aliases & git-prompt scripts to "~/take-me-home"
# * Install z.sh
# * Install Van-Go.sh

# Uninstall/Revert this script by running:
# `$ source leave-home`

# Store the repo's folder path (this script-file's directory)
REPO="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Update & Upgrade distro's packages
source $REPO/scripts/refresh-disro

# Set Environment (git, node, npm)
source $REPO/scripts/install-git
source $REPO/scripts/config-git
source $REPO/scripts/install-node
source $REPO/scripts/install-npm

# Folder paths
TMH=$HOME/take-me-home
BACKUPS=$TMH/backups

# -p, --parents = no error if existing, make parent directories as needed
mkdir -p "$TMH"
mkdir -p "$BACKUPS"

# The following section alternates the following files:
#   ~/.bashrc
#   ~/.inputrc
#   ~/.vimrc
# ---------------
# If a file exists then it must have a backup - but only once, originals only,
# in case this script runs more than once. (see './leave-home' for more info)
# 
# So backup file if exists in $HOME (~/) but not in $backeups
# `ln -f` for overwriting existing files/links.

# .bashrc
if [ -f ~/.bashrc ] && [ ! -f $BACKUPS/original-bashrc.bkp ] ; then
    mv ~/.bashrc $BACKUPS/original-bashrc.bkp
fi
ln -f $REPO/home/.bashrc $HOME

# .inputrc
if [ -f ~/.inputrc ] && [ ! -f $BACKUPS/original-inputrc.bkp ] ; then
    mv ~/.inputrc $BACKUPS/original-inputrc.bkp
fi
ln -f $REPO/home/.inputrc $HOME

# .vimrc
if [ -f ~/.vimrc ] && [ ! -f $BACKUPS/original-vimrc.bkp ] ; then
    mv ~/.vimrc $BACKUPS/original-vimrc.bkp
fi
ln -f $REPO/home/.vimrc $HOME


# take-me-home dependency scripts:
# aliases
# git-prompt
# ----------
# `ln -f` for overwriting existing links.

# aliases
ln -f $REPO/home/aliases.sh $TMH

# git-prompt
ln -f $REPO/home/git-prompt.sh $TMH


# z, jump around
# https://github.com/rupa/z
echo
git clone https://github.com/rupa/z.git $TMH/z

# Van-Gosh, A color library for 256 colors terminals
# https://github.com/taitulism/van-gosh
echo
git clone https://github.com/taitulism/van-gosh.git $TMH/van-gosh

unset REPO
unset TMH
unset BACKUPS

source ~/.bashrc

echo 'Ahh, Feels like home :]'
