#!/usr/bin/env bash

# install git if not exist

echo 'Checking git...'
which git &>/dev/null

if [ "$?" = 0 ] ; then
	git --version
else 
	echo 'Installing git...'
	sudo apt install git
fi

prompt='Config git? [Y/n] (default "Yes")'
read -p "$prompt" configGit

# TODO: handle answer for "no"
# -z for Zero-length (empty string)
if [ "$configGit" = 'n' ] ; then
	unset configGit
	source ./config-git
fi