#!/usr/bin/env bash

echo
echo 'Checking NPM...'
which npm &>/dev/null

if [ "$?" = 0 ] ; then
	echo
	npm outdated -g
	echo
	read -p 'Upgrade npm to latest version? [Y/n] '

	[ "$REPLY" != 'n' ] && sudo npm install npm@latest -g
else 
	echo 'Installing NPM...'
	sudo apt install npm
fi
